### PR TITLE
Add preliminary support for private dependencies using builtins.fetchGit

### PR DESCRIPTION
**Pull request by adisbladis**
Add preliminary support for private dependencies using builtins.fetchGit
    
Using this API looks like:
``` nix
buildGoApplication {
  srcOverrides = self: super: {
    "github.com/BurntSushi/toml" = super."github.com/BurntSushi/toml".override { private = true; };
  };
}
```
    
Outstanding issues:
- Nix has issues dealing with short revs ( https://github.com/NixOS/nix/issues/4694 )
- Param passing heuristics to fetchGit needs to be nailed down.

### CODE REVIEW

**Comment by cstrahan** [comment]
Nice!

Think you might be able to incorporate some of https://github.com/tweag/gomod2nix/pull/11 to resolve the full git rev/SHA?

**Comment by adisbladis** [comment]
I have started looking at adding short rev support to Nix so we don't have to add any more metadata.

**Comment by jgresty** [comment]
Is this patch waiting for upstream changes? Is there any other work that needs doing to support private repos other than what is outlined in this PR?

**Comment by pho** [comment]
Hi, just bumping this up to see if there is any reply to the previous comment questions :)

**Pull request closed without merging**
